version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
       - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    volumes: 
      - .:/demo-ruby
    ports:
      - '6379:6379' # port web access: port docker container use
      

  sidekiq:
    depends_on: 
      - redis
    build: 
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes: 
      - .:/demo-ruby
      - '/demo-ruby/tmp'
    environment: 
      REDIS_URL: redis://redis:6379/0

  web:
    build: .
    tty: true #use debug binding.pry in rails console
    stdin_open: true #use debug binding.pry in rails console
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/demo-ruby
    ports:
      - "3000:3000"
    depends_on: #when use docker network brige or use links then docker different network host
      - db
      - redis
      - sidekiq
