version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
       - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/demo-ruby
    ports:
      - "3000:3000"
    depends_on:
      - db
